planetdecred/dcrlibwallet

go.mod, go.sum, mobilewallet.go
This also fixes travis build error.
=> multi: use only dcrwallet main branch in go modules.

dcrlibwallet.go, response.go, ticket.go
Add StakeInfo and GetTickets functions to dcrlibwallet.
=> Add StakeInfo and GetTickets to dcrlibwallet

.travis.yml, badgerdb/bucket.go, dcrlibwallet.go
Closes #11 
This also includes a cleanup of all unused variables.
=> log: remove logs for invalid wallet address

README.md
A newbie like me might confuse the method of cloning the repository.  This makes the process more straightforward.
=> specify method of cloning repository

dcrlibwallet.go, log.go
This is not what was causing 0 peers, just something I found along the way.  The addrmngr directory was pointing to a non-existing directory.  It now receives the intended directory.  Also added addrmngr output to logs for future debugging.
=> adrmngr: fix dir and add log

go.mod, go.sum
This pull request changes the current wallet version used from v1.3.0 to v1.2.3
=> Change wallet version to v1.2.3

transactions.go
Resolves https://github.com/raedahgroup/dcrios/issues/419
=> fix: use -1 as block height for mempool txs

badgerdb/db.go, dcrlibwallet.go, sync.go, syncnotification.go
This pull request adds a delete function to dcrlibwallet package to enable users delete wallet without errors.
=> Add delete wallet function

sync.go, syncnotification.go
This helps the app reset the display back to normal view
=> rescan: broadcast sync cancelled when rescan is cancelled

transactions.go, types.go
This change makes it easier to query transactions based on type or direction. This also removes sorting of transactions from the frontend and makes it fully based in dcrlibwallet.
Closes #28
=> transactions: add function to query transactions with filter

wallet.go
This adds enables creation of watching only wallet from public passphrase and extended public key.
=> wallet: add CreateWatchingOnlyWallet function

txandblocknotifications.go, txhelper/helper.go, txhelper/types.go, txindex.go, txindex/db.go, types.go
Also use the same set of tx type constants during tx decoding and indexing.
=> fix tx indexing -> check for existing tx error

addresshelper/helper.go, badgerdb/db.go, sync.go, syncnotification.go, ticket.go, txparser.go
Remove unnecessary conversions, format import and remove unused struct(SyncErrorCode).
=> Fix lint errors

accounts.go
Refactor `accounts.go` to remove duplicated code relating to fetching account details.
=> fix accounts iterator bug: account.walletId always 0

log.go
This will help in tracing log source for logs coming from client apps that make use of dcrlibwallet.
=> log: add exported Log function with tag parameter

multiwallet.go, spv/go.mod, spv/go.sum, sync.go, txandblocknotifications.go
See https://github.com/decred/dcrandroid/issues/444
- Fix concurrent map read and map write panic
=> Restart sync after creating/deleting a wallet

errors.go, multiwallet.go, wallet.go
This adds wallet creation to the new wallets only and It'll be the sync start point for new wallets.
=> Add wallet creation time for new wallets

address.go, message.go, multiwallet.go
VerifyMessage & IsAddressValid were moved to multi-wallet since it does not depend on a wallet.
- Also added AllWalletsAreWatchOnly function
=> Move VerifyMessage & IsAddressValid functions to multiwallet

spv/sync.go
This will prevent a bug that'll occur if the wallet with the lowest chain tip does not have the lowest rescan point. The error can be recreated by creating 2 new wallets and trying to sync. I've tested the implementation and it fixes the bug.
=> spv: use wallet with lowest rescan point to find the lowest rescan point

multiwallet.go, spv/sync.go, syncnotification.go, utils.go
- Fix backup function not saving files correctly.
- Fix sync error caused by fetching block locator from the wrong wallet.
=> Minor fixes

README.md, decodetx.go, go.mod, internal/loader/loader.go, log.go, multiwallet.go, multiwallet_utils.go, spv/go.mod, spv/sync.go, sync.go, syncnotification.go, transactions.go, txauthor.go, txhelper/changesource.go, txhelper/outputs.go, txindex.go, txindex/filter.go, utils.go, wallet.go
Rename imports containing "raedahgroup" to "planetdecred" following repository ownership transfer.
=> Rename imports for "raedahgroup" to "planetdecred"

multiwallet.go, proposals.go, types.go
This adds a function that fetches decred proposals from the politea API. 
Fixes #152
=> Fetch proposals from API

accounts.go
Remove redundant code and use GetAccount() to fetch each account.
=> Simplify GetAccounts function

ticket.go
This PR is update ticket.go 
- TicketPrice use wallet context like `wallet.shutdownContext()` instead of pass it as param
- Fix bug`getTickets` crashed when t.Spender is nil
=> Update get price and get list for tickets

types.go, vspd.go
Fix #171 
This PR fix issues with server response request unmarshal.
=> Fix vspd server response request unmarshal bug

spv/backend.go, spv/log.go, spv/rescan.go, spv/sync.go
The code of the spv module is updated to tally with dcrwallet v1.6.3 spv module.
=> Upgrade spv module to dcrwallet v1.6.3

transactions.go
Currently the only way to fetch multi wallet transactions is by decoding json result from `GetTransactions` function.
=> multiwallet: add GetTransactionsRaw function

account_mixer.go, internal/loader/loader.go, internal/loader/log.go, types.go, utils.go
Also update the mixing server url.
=> update loader pkg to be on par with upstream pkg

spv/backend.go, spv/sync.go
Update spv pkg files to match those in https://github.com/decred/dcrwallet/tree/v2.0.0-rc3/spv.
The exception is the `(s *Syncer) DisableDiscoverAccounts()` added upstream for external consumers of the upstream pkg, for which we have no need currently. It can be added later if the need for it arises.
=> update spv pkg to match dcrwallet's v2.0.0-rc3 spv module

ticket.go
Fix #229.
This PR resolves issues with incorrect password passing through when purchasing ticket.
=> fix PurchaseTickets password bug

address.go
Resolves https://github.com/planetdecred/dcrandroid/issues/483
In addition to incrementing the last returned address index, the
NextAddress method now also returns the address at the newly
incremented index.
This also ensures that CurrentAddress always returns the last requested
address.
=> NextAddress should return a different address from CurrentAddress

spv/sync.go
Resolves https://github.com/planetdecred/godcr/issues/827
The sidechain acts as a temporary storage location for blocks that
are fetched from a remote peer, prior to being added to each wallet's
mainchain. While unlikely, but especially in the case of a reorg, the
data in the sidechain might become inconsistent because it depends on
wallet-specific information such as blocks already existing in each
wallet's mainchain and blocks that become re-orged from a wallet.
This change ensures that the sidechain data remains consistent for each
wallet.
=> spv syncer: maintain different sidechains for each wallet

consensus.go
Resolves https://github.com/planetdecred/godcr/issues/883
This PR accounts for the following agenda status types `defined`, `started`, `failed`, `lockedin`, `locked in` and `active`.
These statuses were not previously accounted for, which led to a crash in the client app
=> add agenda status types for failed and locked in agendas
