planetdecred/dcrlibwallet

- dcrlibwallet.go
- log.go
This checks if the netType string parameter passed to `NewLibWallet` is for a valid network type and returns an error if not.
This also ensures consistency when determining the wallet database directory using the network type param name.
> Fix netType usage in NewLibWallet, add WalletOpened function

- dcrlibwallet.go
- go.mod
- go.sum
- log.go
- response.go
Transactions are indexed after every sync for faster loading. It's useful in the case where transactions need to be queried in a specific order or based on the transaction attributes. It's faster because all transaction details are saved so it doesn't need to be fetched from the wallet because the wallet is slower when fetching transactions compared to using storm db.
> Index transactions using storm db

- txindex/filter.go
- txindex/read.go
This PR added more filter definition functions to the `ReadFilter` struct and updated the `txindex.DB`'s `createTxQuery` function to use the new query mechanism.
The new functions are 
`AndWithTxTypes`
`AndForDirections`
`OrWithTxTypes`
`OrForDirections`
`AndNotForDirections` and
`AndNotWithTxTypes`
> Added added more query support to ReadFilter

- syncprogressestimator/syncprogressestimator.go
If network connection is lost, number of connected peers drop to 0. When network is restored, the peers reconnect. This causes the sync callbacks to be re-invoked. Currently, the following sync callbacks are ignored if the wallet was already previously synced:
- `OnFetchedHeaders`
- `OnSynced` - triggered when sync ends
- `OnSyncEndedWithError`/`OnSyncError` - triggered when error occurs during sync
dcrandroid only ignores `OnFetchedHeaders` callback after a previously completed sync.
This PR allows `OnSynced` and `OnSyncEndedWithError`/`OnSyncError` callbacks to always be broadcasted, regardless of whether sync was completed previously.
> always broadcast sync completed methods

- sync.go
- syncnotification.go
Add `syncProgressListener.OnSyncCanceled` callback for when sync context is canceled. Sync context is canceled from `lw.CancelSync()`, which causes `syncProgressListener.OnSyncCanceled` callback to be broadcasted.
> Sync improvements: differentiate sync cancel from error

- sync.go
- syncprogressestimator.go
If the sync process gets interrupted for any reason, the sync estimation code currently does not discard the period of inactivity when calculating eta.
This PR adds a method for client apps to notify dcrlibwallet when sync process gets interrupted for some time to ensure that dcrlibwallet's estimated eta remains approximately accurate by accounting for lost time.
This PR also attempts to minimize bogus address discovery ETAs by setting a minimum estimate of 2 minutes for address discovery in situations where total headers fetch time is so small that address discovery estimate is negatively affected.
> account for sync inactivity periods when estimating eta

- sync.go
- syncnotification.go
This resolves 2 crash errors gotten from running dcrios with dcrlibwallet/master:
- attempting to access nil `lw.activeSyncData`)
`lw.activeSyncData` is nil if sync is not currently active, either because it was never started with `lw.spvSync/rpcSync` or because sync was either canceled or sync ended (with or without error).
- attempting to update connected peer count after sync ends
> ignore subsequent sync callbacks after sync completes

- txauthor.go
- utils.go
`lw.constructTransaction` stalls indefinitely when the minimum possible int64 value is passed as amount. This PR fixes that bug by checking amount values before constructing txs and also exporting the max dcr and atom amounts for use by client apps in in-app validation.
> export max amount constant, check amount values for new txs

- transactions.go
The log displayed when indexing transaction displays the best block height as the transaction height. This fixes it by displaying the block height gotten from the currently indexed transactions block header as the transaction height.
> Use correct endHeight for IndexTransactions log

- syncnotification.go
- Correct total time remaining calculation during stage 3 (headers rescan)
- Adjust ETA calculation for stage 1 (headers fetch progress). See https://github.com/raedahgroup/dcrlibwallet/issues/43#issuecomment-498949399
> Sync estimate calculation improvements

- sync.go
- syncnotification.go
This function helps the app resume the sync estimates from last progress instead of waiting for the next sync progress.
> Add function to publish last sync progress

- sync.go
- syncnotification.go
- types.go
- Include rescan time remaining with block rescan progress report for sync and blocks rescan.
- Trigger sync completed callback when block rescan ends, to notify UI of completion.
- Broadcast previous sync progress report to newly added sync listeners when they are registered in the middle of a sync operation.
> Improvements to sync and rescan blocks features

- dcrlibwallet.go
- sync.go
- syncnotification.go
- utils.go
- wallet.go
This code on master causes the `shutdownSignaled` signal to be broadcasted twice. This is especially noticable when `lw.ShutDown()` is called in the process of deleting a wallet. The result is that when a wallet is deleted and recreated, the second signal is processed and the newly created context for sync is canceled almost as soon as it is created.
```
if !IsChannelClosed(shutdownSignaled) {
log.Info("Channel not closed, closing")
close(shutdownSignaled)
}
```
This PR optimizes dcrlibwallet shutdown operations, removing redundant codes (interrupt signal listener included - allowing apps handle all shutdown process internally, calling `lw.Shutdown()` when necessary).
Also removes the need to wait for peer connections to be lost before deleting wallet.
> cleanup shutdown function

- dcrlibwallet.go
- go.mod
- go.sum
- sync.go
Active sync is canceled by canceling the sync context using `lw.cancelSync()`. The sync process does not immediately halt however. This PR adds a `syncCanceled` channel that gets notified when the sync process eventually gets canceled (`syncer.Run` returns) and modifies the shutdown / sync cancellation process to wait for the `syncCanceled` channel to be triggered before proceeding.
> wallet shutdown: wait for sync to completely cancel before closing wallet db

- sync.go
- syncnotification.go
- types.go
- Cancel any active sync and unset the wallet's network backend.
- Include `syncRestarting` flag when notifying callbacks of active sync cancellation. This to enable apps display an appropriate sync status message.
- Separate `RestartSpvSync` and `RestartRpcSync` methods to ensure that the relevant data needed to restart a sync operation is passed in.
> Add RestartSpvSync and RestartRpcSync methods

- dcrlibwallet.go
- sync.go
- transactions.go
- txauthor.go
- utils.go
The previous implementation created a goroutine for each context created with shutdown cancel. This implementation uses one goroutine and stores the cancel functions in a slice which is then looped through and invoked once shutdown signal is received.
This change also fixes a bug that causes the code to be stuck when writing to the shutdown channel and there are zero subscribers on the channel.
> shutdown: use one goroutine to listen for shutdown signal

- dcrlibwallet.go
- go.mod
- sync.go
- syncnotification.go
- transactions.go
- txhelper/types.go
- txindex/db.go
- txindex/filter.go
- txindex/read.go
- txindex/save.go
Create a `txindex` package to enable godcr perform tx index operations when using dcrwallet rpc rather than dcrlibwallet.
A subsequent PR will introduce other walletrpc helper functions to dcrlibwallet, but the changes here are primarily to permit code reusability between godcr and dcrlibwallet instead of writing tx indexing code on both projects.
A tiny change set included also is the added method to retrieve number of connected peers.
This is also a continuation of #6.
> abstract tx index db ops to txindex package

- accounts.go
- go.mod
- types.go
GoMobile does not export `Accounts.Acc` property. This PR resolves this with an iterator. 
This feature is used in PR https://github.com/raedahgroup/dcrios/pull/533
> AccountIterator

- accounts.go
- go.mod
- utils.go
This adds a helper function and it is used to get the HD path for the specified account. The function handles checking if the wallet is using a legacy coin-type or not, to determine what HD path belongs to it.
> accounts: add legacy HD paths and a function to get HD path for account

- go.mod
- multiwallet.go
- rescan.go
- sync.go
- txindex.go
- txindex/save.go
- types.go
- wallet.go
This change adds a listener interface that broadcasts updates to the frontend when the wallet is rescanning. Transactions saved to the database are cleared after a successful rescan and an index operation is started from block height 0 to the latest block.
Closes #71
> Reindex transactions after rescan and add rescan progress listener

- spv/sync.go
This will avoid a crash caused when the lowest chain wallet doesn't have the block returned from the lowest rescan point.
> spv: use rescan point from lowest chain wallet

- .github/workflows/build.yml
- .github/workflows/docker.yml
- Dockerfile
- run_tests.sh
Add a test  [script](https://github.com/raedahgroup/dcrlibwallet/pull/82/files#diff-c08082f308f76bbde9882b88503605be) which invokes `go test` and `golangci-lint`.
Add two github actions :
- `Go` : Runs `go build`, `go test` and `go vet`.
- `Docker` : Runs the test script.
Pipeline results can be viewed here: https://github.com/RogueElement/dcrlibwallet/actions.
Currently `Docker` fails because there are linting error in the package.
> Add github actions and docker

- sync.go
- syncnotification.go
Account discovery thread runs while sync is canceling and it eventually causes a crash. This pull request fixes it by canceling the account discovery thread before canceling sync.
> sync: close account discovery channel before canceling sync

- rescan.go
- spv/sync.go
- sync.go
- syncnotification.go
- types.go
- utils.go
Ensures that access to ongoing sync data uses mutex locks held for as little time as possible to prevent delays when some other operation attempts to access ongoing sync data.
It is particularly important to unlock the syncData mutex before triggering sync progress listeners registered by client apps, since some of such listeners may perform long-running operations or even try to access ongoing sync data - in which case, an attempt will be made to lock the syncData mutex. In the latter scenario, the attempt to lock the mutex would lead to a deadlock if the mutex was not previously unlocked before the client-registered listener was invoked.
Also fixed a bug with `cancelSync` where initial syncing may have completed and the method is called to disconnect the wallets from the network …
> Refactor syncData mutex to prevent potentially long locks

- syncnotification.go
Sync headers fetch progress constantly shows 100% because it is unable to correctly estimate the number of headers remaining to be fetched. This PR fixes that estimation code.
> fix bug with sync headers fetching progress calculation

- sync.go
- syncnotification.go
Wallets are sometimes unlocked without a time limit before sync is started, so that accounts discovery may be performed.
Currently, such wallets are only re-locked when account discovery completes. This PR ensures that all wallets are re-locked even if sync is canceled or errors before account discovery completes.
Also,
- export wallet.IsSyncing() and wallet.IsSynced()
> lock wallets if sync errors or is canceled

- address.go
- errors.go
- multiwallet.go
- multiwallet_config.go
- multiwallet_utils.go
- sync.go
- txandblocknotifications.go
- types.go
- utils.go
- wallet.go
- wallet_config.go
- wallets.go
- `AllWallets()` and `WalletsIterator()` methods for client apps to access all wallets info
- Add `wallet.IsRestored` property to track restored wallets and ensure that address discovery is completed for such wallets before new addresses are derived.
- Fix bug with linking an existing wallet that uses a non-default public passphrase. Also added helper methods for easily migrating v1 wallets to the new multiwallet structure.
- Implement wallet-specific config reading/writing.
> multi: add multiwallet helper functions, fix link existing wallet bug, implement per-wallet config handling

- go.mod
- go.sum
This addresses a crash that occurs when installing v1.0.1 dcrlibwallet on top of v1.0.0, caused by having [two opened cursors](https://github.com/decred/dcrwallet/blob/master/wallet/udb/upgrades.go#L968) in dcrwallet wallet db upgrade.
> Upgrade wallet module to fix badger db panic

- dcrlibwallet.go
Fixes a bug that causes rescan remaining time estimation to be way off. The bug occurred because the rescan function was not sending a notification when rescan started which is when dcrandroid resets the estimates and the fix was done by sending a “rescan started” to the registered notification listeners.
> rescan: send a notification when rescanning starts

- multiwallet_utils.go
`RootDirFileSizeInBytes` function returns the sum of every file size in multi-wallet directory. 
Required by https://github.com/decred/dcrandroid/pull/440.
> Add RootDirFileSizeInBytes utility function

- accounts.go
- multiwallet_config.go
- txauthor.go
- utils.go
- wallet_config.go
Change from `wallet.NewUnsignedTx` to `multiwallet.NewUnsignedTx` is done to enable the `NewUnsignedTx` method access the user-configured `SpendUnconfirmedFunds` setting.
Also enable access to the `SpendUnconfirmedFunds` setting from wallet methods and remove `requiredConfirmations` parameters from wallet methods.
> send: change NewUnsignedTx to multiwallet method, add TxAuthor helper methods

- multiwallet_config.go
IOS uses both Touch ID and face ID so it is appropriate we name the config key to "UseBiometricConfigKey".
required by https://github.com/raedahgroup/dcrios/pull/613
> renamed finger print key to biometric key

- multiwallet_utils.go
- syncnotification.go
Fixes recurrent unlock wallet bug by removing unnecessary fetch of wallet from database and mark wallet as discovered account in synced function. `HasDiscoveredAccounts` was saved only when address discovery ended and wallets that are already synced did not do address discovery so in the case of an error in saving `HasDiscoveredAccounts`, the wallets would need to discover addresses.
> Fix recurrent unlock wallet bug

- utils.go
fixes inaccurate result during wallet sync when calculating how far behind in days a wallet is compared to the latest block height.
> fix days behind calculation

- spv/sync.go
This PR fixed the issue of headers getting fetched out of order by sending fetch header progress notification for only best block.
closes #126
> SPV: send fetch header progress notification for only best block

- spv/sync.go
Fixed a bug that caused transaction notifications not to be delivered because rescan point is not always nil.
Closes #109
> spv: fix incoming transaction notifications

- multiwallet.go
- syncnotification.go
- txandblocknotifications.go
This fixes a bug that causes the app's UI to lag when fetching headers
Closes #133
> Register transaction notification after completing sync

- errors.go
- multiwallet.go
- multiwallet_utils.go
- multiwallet_utils_test.go
- utils.go
- wallet.go
Addresses an issue where verify seed function returns ErrInvalid for an incorrect passphrase and also fixes a bug where the seed of an already backed up wallet is attempted to be re-encrypted meanwhile the encrypted seed is empty and that throws an uncaught error.
> Fix seed encryption errors

- multiwallet.go
The seed for restored wallets should not be saved since they do not require backup.
> Do not save seed for restored wallets

- spv/sync.go
- sync.go
- syncnotification.go
This correctly calculates the progress of sync headers fetch operation. It achieves this by comparing the total headers fetched in the current sync operation against estimated number of headers left to be fetched.
Fixes #95
> fix sync progress calculation error

- spv/sync.go
- transactions.go
This will help rebroadcast transactions stuck in the pending state.
See https://github.com/planetdecred/dcrandroid/issues/480
> Add PublishUnminedTransactions function

- txauthor.go
This PR verifies an address passed to the ```AddSendDestination``` function. It returns an error if the address is invalid. 
Fixes #100
> verify address before adding to send destination

- multiwallet.go
- sync.go
- syncnotification.go
This addresses sync canceling hanging forever at `Address manager shutting down`. This would occur when both `mw.listenForTransactions()` and `mw.CancelSync()` were waiting on the `syncCanceled` channel.
fixes #141
> fix hang on sync canceling

- multiwallet_utils.go
- run_tests.sh
Remove unparam from ci lint and remove log from non-multiwallet functiom to avoid panic during testing.
> Fix GitHub action build errors

- badgerdb/bucket.go
- badgerdb/db.go
- multiwallet.go
This fixes a bug that causes the LockedByTickets balance to always be 0 due to incomplete information returned by the badger database driver and it's caused by the [cursor](https://github.com/decred/dcrwallet/blob/master/wallet/udb/txmined.go#L3546) used to iterate unspent ticket commitments. The items in the database are grouped by prefixes(technically database tables), when iterating the unspent ticket commitments the cursor found an item with a another prefix an assumed the iteration was done meanwhile it could easily skip that to find all the required data.
Closes #154
> Fix incorrect account balance bug

- sync.go
- types.go
`PeerInfo()` returns information about currently connected spv peers in json.
```
[
{
"id": 1,
"addr": "127.0.0.1:19108",
"addr_local": "127.0.0.1:53402",
"services": "00000005",
"version": 8,
"sub_ver": "/dcrwire:0.4.0/dcrd:1.7.0(pre)/",
"starting_height": 559536,
"ban_score": 0
}
]
```
> Add PeerInfo() to get a list of connected spv peers

- account_mixer.go
- accounts.go
- badgerdb/db.go
- errors.go
- spv/sync.go
- txandblocknotifications.go
- txauthor.go
- txindex.go
- wallet.go
- wallet_config.go
- add ClearMixerConfig to reset account mixer config
- rename instances of 'Change' to 'Unmixed'
- remove wallet lock timeout when creating an account
> account mixer: add ReadyToMix to determine if wallet is ready to mix

- account_mixer.go
- go.mod
- go.sum
This adds an option to either allow dcrlibwallet to create accounts needed for the cspp mixer or use SetAccountMixerConfig to setup the mixer using existing accounts.
> account mixer: add CreateMixerAccounts to help create accounts needed for cspp mixer

- log.go
Currently dcrlibwallet uses its own internal log system which is fine but as dcrlibwallet is mostly used as a package and not a standalone program this doesn't allow programs that uses dcrlibwallet to control the logging (save for setting the log levels).
This pull request will allow external programs to use their own log systems in place of this internal system allowing greater control of logging output. 
For example, in [godcr](https://github.com/planetdecred/godcr) this will allow a cross platform way for the application to display a page showing the log output.
This doesn't replace the current system in any capacity, dcrlibwallet will still use its own system if no logger is used.
> Allow dcrlibwallet to use an external logger

- syncnotification.go
This fixes a bug where a received transaction does not show up until transaction indexing is done during manual rescan or next sync because sync notifications are ignored once the initial sync completed notification is received. The bug was fixed by indexing transactions whenever `synced` notification is received and all wallets are synced.
> [release-v1.5] Index transaction everytime synced function is called

- multiwallet.go
- wallet.go
The `DBDriver` function will help the client app know what database driver the wallet was created with.
> Add function to get wallet db driver and declare db driver constants

- wallet.go
This pr removes the `DbDriver` function added by https://github.com/planetdecred/dcrlibwallet/pull/182, the function already gets added by gomobile during the build and it causes a function name conflict.
> Remove db driver function to avoid gomobile functions conflict

- rescan.go
- syncnotification.go
- txindex.go
- walletdata/save.go
This fixes a bug where a received transaction does not show up until transaction indexing is done during manual rescan or next sync because sync notifications are ignored once the initial sync completed notification is received. The bug was fixed by indexing transactions whenever `synced` notification is received and all wallets are synced.
Closes #180
> Index transaction everytime synced function is called

- multiwallet.go
- wallet.go
- walletdata/db.go
Following https://github.com/planetdecred/dcrlibwallet/pull/163, tx db name was renamed to `walletData.db` from `tx.db`. This change ensures any wallet with the old `tx.db` will get renamed to the new name.
> tx index: rename old tx db to new walletdata db name

- politeia.go
- politeia_sync.go
- types.go
Closes #179 
This pr fixes a bug where a proposal is shown under the wrong category which happens after a proposal is updated. The following bugs are fixed by this pr:
- Skip abandoned proposals when checking for updates.
- Fix incorrect no votes & category on an updated proposal.
- Fix false positive deep equal comparison by setting updated proposal id.
- Set Token property as unique under Proposal struct.
> Fix bugs when updating proposals

- decodetx.go
The amount for ticket & revoke transaction was not set and it made the transaction decoder use the transaction fee as the amount instead of the ticket purchase amount. The pr fixes that by setting the amount to the appropriate transaction input/output.
Closes #177
> Set amount for ticket & revoke transactions

- accounts.go
The total balance returned was including voting authority, hence showing the user an incorrect watch only wallet balance.
This PR fixes that
> fix wrong total balance being returned

- sync.go
This PR add missing case in GeneralSyncProgress  function to help mobile get notification when app in background
> Add missing case in GeneralSyncProgress function

- decodetx.go
- errors.go
- politeia_client.go
- politeia_sync.go
- transactions.go
- txauthor.go
- txhelper/types.go
- txindex.go
- txparser.go
- types.go
- vspd.go
- walletdata/db.go
- walletdata/filter.go
This change allows easy filtering of mixed transactions and the tx db version number is also incremented to enable wallets to reindex their transactions and correctly specify the tx type of old mixed transactions.
> Add Mixed transaction type and filter 

- account_mixer.go
- multiwallet.go
Previously the Account Mixer Notification listeners weren't being called with unique identifiers, this caused newly opened pages to override the callback listeners set in previous pages. the resulting effect of this was the user's screen not going to sleep after the mixer had ended while they are on some pages of the app
This new change allows the callback listeners to be triggered simultaneously across all pages that calls it in the client app allowing the user's screen to sleep no matter what page they are viewing
> pass unique identifiers to the account mixer notification listeners

- account_mixer.go
- txauthor.go
- types.go
- wallet_config.go
Sending the change of transactions created from the mixed account to unmixed will allow the change coins to be mixed before spending.
> Send mixed account transactions change to unmixed account

- ticket.go
- transactions.go
- txindex.go
- txparser.go
- types.go
- wallet.go
- walletdata/db.go
- walletdata/filter.go
- walletdata/read.go
- Add tx filters for voted and revoked tickets.
- Add function to get ticket spender transaction.
- Add transaction timestamp and block height to storm index
This adds functions for getting transaction and staking overview which returns a summary count of different transaction and staking filters.
> Add transaction and staking overview

- dexdcr/go.mod
- dexdcr/go.sum
Remove the replace directive that was pointing to a local dcrlibwallet directory which prevents downloading the dexdcr module with `go get github.com/planetdecred/dcrlibwallet/dexdcr@master`.
> dexdcr: bump dcrlibwallet require version

- txandblocknotifications.go
- types.go
Prevent potential deadlocks by making provision for tx and
block notification callbacks to be invoked asynchronously.
One such deadlock scenario that necessitated this change was
the wallet ticket purchse function blocking access to the
wallet balance method while sending a new transaction ntfn,
and a new tx ntfn handler tried to synchronously fetch the
wallet balance. The handler could not fetch the wallet balance
because it is blocked by the ticket purchase function and the
ticket purchase function could not complete its process and
unlock the wallet balance feature because it was waiting for
the ntfn handler to complete.
> add async tx and block notification listeners

- multiwallet.go
Simply log an error message and track wallets that failed
to load rather than preventing the initialization of the
MultiWallet instance.
> ignore wallet load errors on multiwallet init

- multiwallet_utils.go
- sync.go
This Pr gets the wallet activation/deployment block height.
This aim to prevent the godcr error `wallet.NextStakeDifficulty: inactive deployment: DCP0001 is not known to be active` when getting ticket price from a wallet when it has not reached the sync activation height on mainnet network.
> get wallet deployement/activation block height

- multiwallet.go
Such wallets are unusable and  would return an error when
a caller later tries to open all loaded wallets using
mw.OpenWallets.
> don't load wallets with missing db files on startup

- go.mod
- go.sum
When try to build lib for android, we have the problem:
`github.com/planetdecred/dcrlibwallet/vendor/github.com/lib/pq/user_posix.go:13:6: userCurrent redeclared in this block`
This issue occur in user_posix.go file and the lib/pq have new version update for fix it.
This PR update lib/pq to new version for fix it
> update lib/pq to v1.10.4 build lib for android

- go.mod
- multiwallet_utils.go
- wallet.go
Since existing wallet seeds are not stored unecrypted and may not even be
stored at all if the user has backed up the seed, the check for already-used
seeds relies on comparing the account xpub of the default account of existing
wallets with the xpub of the same account using the new seed.
> implement mw.WalletWithSeed method to identify already used seeds

- multiwallet_utils.go
This prevents a potential, avoidable error with `mw.WalletWithXPub`.
> ignore imported accounts when checking xpubs

- .github/workflows/build.yml
the install section of the official golangci-lint website(https://golangci-lint.run/usage/install/) shows there's a new URL used to install the golangci-lint binary which is https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh the dcrlibwallet workflow was attempting to use https://install.goreleaser.com/github.com/golangci/golangci-lint.sh, which is an old method of installing the binary and no longer works, causing the workflow to fail
The fix was to replace the outdated URL with the one recommended from the golangci-lint website
> update the url endpoint for installing the golint binary
